/**
 * Generates supabase/migrations/0020_permissions_seed.sql from the TypeScript source of truth (src/lib/admin/permissions.ts).
 * The migration REPLACES role_permissions and workflow_transitions (0004 seeded the Phase 2A subset; it is left untouched as history).
 * Reference data (states, departments, …) is NOT generated any more: the database is its source of truth (see 0004/0005 + admin screens).
 */
import { writeFileSync } from "node:fs";
import { ROLES, permissions, workflow } from "../src/lib/admin/permissions";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const out: string[] = ["-- GENERATED by scripts/gen-sql.ts — do not edit by hand. Source: src/lib/admin/permissions.ts", "", "delete from role_permissions;", "delete from workflow_transitions;", ""];
out.push("insert into role_permissions (role, action) values");
out.push(ROLES.flatMap((r) => permissions[r].map((a) => `  (${q(r)}, ${q(a)})`)).join(",\n") + ";\n");
out.push("insert into workflow_transitions (kind, from_status, to_status, permission) values");
out.push(workflow.map((t) => `  (${q(t.kind)}, ${q(t.from)}, ${q(t.to)}, ${q(t.action)})`).join(",\n") + ";\n");
writeFileSync("supabase/migrations/0020_permissions_seed.sql", out.join("\n"));
console.log("wrote 0020_permissions_seed.sql");
